### ISSUE TITLE
Python 3.9 Issue

### ISSUE THREAD

**Issue by royord** [COUR4G3/python-pppd#10]
Running

```
from pppd import PPPConnection

ppp = PPPConnection(call='webcam_num0')
print(ppp.connected())
```

Using Python 3.9 gives the following error.

```
Traceback (most recent call last):
  File "/home/pi/ppp_py.py", line 3, in <module>
    ppp = PPPConnection(call='webcam_num0')
  File "/usr/local/lib/python3.9/dist-packages/pppd.py", line 82, in __init__
    self.output += self.proc.stdout.read()
TypeError: can't concat NoneType to bytes
```

**Comment by COUR4G3** [comment]
Oh, I just love non-blocking IO and Python ;_;

Seems something changed in 3.9 so will have to check if the result of `None` and not concatenate. It should be a quick patch, will see if I get some time to patch it and do a new release on PyPi.

**Comment by royord** [comment]
Let me know if there's anything that I can do to help, I may also add some additional items to the readme based on python3 when I am able to use the library. My project that I'm working on will greatly benefit from ability to use this library. Thanks

**Comment by COUR4G3** [comment]
I have pushed a fix to master, I don't have a working PPPD setup to test it on, so if you'd like to take a look at it and I can do the release the PyPi. And if you have any contributions to the documentation or anything you are more than welcome to make a PR.

**Comment by royord** [comment]
I cloned the repo and used the install script and still get the same error.

To be clear I can ```pon webcam_num0``` without issue.

**Comment by wbarnha** [comment]
I also encountered this issue and it would be appreciated if a release to PyPi could be made. I'm not sure how @royord is still encountering this issue, but the fix above should solve my issue.
